<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	  <Title>AutoLicensing</Title>
	  <Authors>mhmdsmdi</Authors>
	  <Description>AutoLicensing is an open-source license manager.</Description>
	  <PackageProjectUrl>https://github.com/mhmmdsmdi/AutoLicensing</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/mhmmdsmdi/AutoLicensing</RepositoryUrl>
	  <AssemblyVersion>2.3.0</AssemblyVersion>
	  <FileVersion>2.3.0</FileVersion>
	  <Version>2.3.0</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoLicensing\AutoLicensing.csproj" />
  </ItemGroup>

</Project>
